### ISSUE TITLE
Reusable beverage containers?

### ISSUE THREAD

**Issue by mr-fuller** [Esri/devsummit-feedback#11]
According to the stats from the final session, attendees consumed a lot of coffee and other beverages during the conference, and since single-use cups were provided, I imagine a lot of waste was generated, although I think all the cups were made of paper or plants, so it's great that the materials were recyclable or degradable; however, did the conference planning team consider providing attendees with a reusable beverage container? 

Of course, if a reusable cup/mug can't be made from recyclable or degradable materials, it might make more sense to keep using single-use cups from a sustainability perspective, although I can imagine there are other factors in play as well.

I would appreciate your consideration on this issue.

**Comment by jgravois** [comment]
> did the conference planning team consider providing attendees with a reusable beverage container?

i bring my own water bottle with me, but its easy to forget so it'd be cool to see a reminder go out with the rest of the info that's provided to attendees in advance.
