### ISSUE TITLE
3D GeoJSON

### ISSUE THREAD

**Issue by hunger1** [Esri/devsummit-feedback#19]
I did not think to ask the question in advance, but there is a question I would have liked to have asked. There was a lot of talk during the week about GeoJSON and a lot of talk about 3D. The GeoJSON standard does not provide for 3D. Perhaps there is enough interest out there to convene an IETF working group (or reconvene the original one) to extend the GeoJSON standard to include 3D, unless, of course, there is a reason why 3D GeoJSON would be a really bad idea.

**Comment by jgravois** [comment]
RFC 7946 already allows for coordinates that articulate elevation.

https://tools.ietf.org/html/rfc7946#section-3.1.1

for a more robust open source 3D scene specification, check out i3s.

https://github.com/esri/i3s-spec.

**Comment by hunger1** [comment]
Thank you. Someone told me that it didn't and I clearly did not read the spec closely enough.
