### ISSUE TITLE
Mobile Map Packages with Quartz

### ISSUE THREAD

**Issue by snodnipper** [Esri/devsummit-feedback#3]
We have learned some great things about quartz and Mobile Map Packages.  Is there a single place for documentation on Mobile Map Packages in Quartz?

Specifically, we learned today from Euan Cameron that the Quartz Map Packages will be SQLite.  I asked, however, about _updates_ for Map Packages - specifically around vector tiles.
Euan assured me that Vector Tiles will be not be downloaded multiple times by multiple maps (covering the same area), that vector tiles won't be stored in the SQLite and that the (http) etags will be checked for individual tiles to ensure that users have the latest basemap mapping.  It therefore seems that the workflow will be different for basemaps.

**Comment by EuanCameron** [comment]
The Mobile Map Package support will be release initially in Beta II of the Quartz runtime release.   At this time the SDK documentation will have information on how you can use this as part of your developments.   ArcGIS Pro 1.2 when it is released early next year will have the ability to create MMPKs and the creation process will be documented and available to ArcGIS Pro users.

To be clear, the Mobile Map Package is a compressed archive containing a number of files.   It contains
- Mobile Map(s)
- base map data (these can be vector or raster tile sets)
- operation data that is stored in a mobile geodatabase (a mobile geodatabase uses SQLite as its datastore)
- Locators
- Routing networks

It does not needs to contain all of these but it can.    Typical workflows often see basemap data handled as a separate item, meaning it can be shared amongst multiple MMPKs.

Similar to raster tiles, vector tiles when accessed from a server are not downloaded twice (unless the etag shows there is a difference).

**Comment by snodnipper** [comment]
Excellent, thank you @EuanCameron for the clarification.
