### ISSUE TITLE
Slides, resources & demos

### ISSUE THREAD

**Issue by hhkaos** [Esri/devsummit-feedback#5]
I guess most of the slides would be on the proceedings page, but... could we create a markdown document in this repo with a list of interesting resources & demos?:

**The road ahead and closing Q&A:**
- [Calcite](https://github.com/Esri/calcite-maps)

**User Experience and Interface Design for Web Apps:**
- [GIS Day Map](https://github.com/Esri/gis-day-map)

**Web AppBuilder for ArcGIS Customising and Extending:**
- [ArcGIS Web AppBuilder: Development Tools and Techniques - See more at: http://video.esri.com/watch/4568/arcgis-web-appbuilder-development-tools-and-techniques#sthash.CJaPmpAy.dpuf](http://video.esri.com/watch/4568/arcgis-web-appbuilder-development-tools-and-techniques)

**ArcGIS API for JavaScript Build 3D Web Apps**
- [New_York_City_1836 tiles](http://tiles.arcgis.com/tiles/IEuSomXfi6iB7a25/arcgis/rest/services/New_York_City_1836/MapServer)

**Resources:**
- [Allan Framboise Slides](http://slides.com/alaframboise)

**Comment by EuanCameron** [comment]
That's a great idea.   Look for a page to appear in this repo in the near future.   We will get all the Esri team to add their resources and eventually when the slides of the proceedings are ready we can reference them too.

@JimBarry @alaframboise

**Comment by hhkaos** [comment]
Hi @EuanCameron, I just wanted to share [the proceedings page for this event](http://proceedings.esri.com/library/userconf/devsummit-euro15/index.html) and I also put together a [few of the demos we saw here](https://github.com/esri-es/demos).

I'll see you in Palm Springs during the Dev Summit!

Best,
Raul
