### ISSUE TITLE
Are there plans to support cluster markers in the ArcGIS JavaScript 4.0?

### ISSUE THREAD

**Issue by MapsRus** [Esri/devsummit-feedback#8]
Are there plans to support/create cluster markers in the ArcGIS JavaScript 4.0?

**Comment by JimBarry** [comment]
Nothing specific just yet. It's something the dev teams here at Esri know about and want to do, either as part of the JS API or in Server/Online/Portal. Until then, here is a sample you might find use for: https://github.com/Esri/cluster-layer-js , although that sample in particular uses 3.15.
