### ISSUE TITLE
How does the ESRI Development Team keeps up with emerging software development trends and at the same time to master them all to a high level of proficiency year after year?

### ISSUE THREAD

**Issue by AbdielQuezada** [Esri/devsummit-feedback#9]
Hello Jim,

As according to our conversation at the end of the “Speedgeeking” session, I am reaching out to you with my question for the ESRI Development Team.
 
How does the ESRI Development Team keeps up with emerging software development trends and at the same time to master them all to a high level of proficiency year after year?
 
The GIS community can benefit from this feedback in order to mimic ESRI’s best practices.
 
Thank you,

**Comment by jgravois** [comment]
i mostly use twitter 🐢
